# Generated by Django 5.2.17 on 2026-09-04 01:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='supprimé le')),
                ('code', models.CharField(help_text='Ex. EBONT, DHL, LAF', max_length=20, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('contact_nom', models.CharField(blank=True, max_length=200, verbose_name='contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('contact_tel', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fournisseur',
                'verbose_name_plural': 'fournisseurs',
                'ordering': ['nom'],
            },
        ),
    ]
