# Generated by Django 5.2.17 on 2026-09-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='mode_extraction',
            field=models.CharField(blank=True, choices=[('TABLEAU', 'Tableau (en-têtes)'), ('GRILLE', 'Grille (sans en-tête)'), ('TEXTE', 'Texte libre')], max_length=20, verbose_name="mode d'extraction"),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='regex_numero_serie',
            field=models.CharField(blank=True, help_text='Ex. 24E\\d{10}A\\d{3} (Ebont), \\d{6} (DHL), 030926\\d{7} (LAF).', max_length=200, verbose_name='expression régulière — numéro de série'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='type_article_defaut',
            field=models.CharField(blank=True, choices=[('FLEXITANK', 'Flexitank'), ('HEATING_PAD', 'Heating pad')], help_text='Appliqué aux lignes extraites de ce fournisseur si son catalogue est homogène.', max_length=20, verbose_name="type d'article par défaut"),
        ),
    ]
