# Generated by Django 5.2.17 on 2026-09-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_fournisseur_mode_extraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='seuil_reappro_flexitank',
            field=models.PositiveIntegerField(blank=True, help_text="Alerte si le nombre de Flexitanks en stock de ce fournisseur descend à ce niveau ou en dessous. Vide = pas d'alerte.", null=True, verbose_name='seuil de réapprovisionnement — flexitank'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='seuil_reappro_heating_pad',
            field=models.PositiveIntegerField(blank=True, help_text="Alerte si le nombre de Heating pads en stock de ce fournisseur descend à ce niveau ou en dessous. Vide = pas d'alerte.", null=True, verbose_name='seuil de réapprovisionnement — heating pad'),
        ),
    ]
