# Generated by Django 5.2.17 on 2026-09-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_fournisseur_seuil_reappro_flexitank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='cout_unitaire_flexitank',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Coût d'une unité Flexitank chez ce fournisseur. Vide = valeur immobilisée affichée « — » pour ce type.", max_digits=10, null=True, verbose_name='coût unitaire — flexitank'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='cout_unitaire_heating_pad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Coût d'une unité Heating pad chez ce fournisseur. Vide = valeur immobilisée affichée « — » pour ce type.", max_digits=10, null=True, verbose_name='coût unitaire — heating pad'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='delai_livraison_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Délai moyen entre la commande et la réception, en jours. Sert au calcul du point de commande dynamique. Vide = seuil dynamique non calculable pour ce fournisseur (le seuil manuel ci-dessus reste utilisable, lui, indépendamment).', null=True, verbose_name='délai de livraison (jours)'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='stock_securite_flexitank',
            field=models.PositiveIntegerField(blank=True, help_text='Marge ajoutée au point de commande calculé. Vide = marge de 0.', null=True, verbose_name='stock de sécurité — flexitank'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='stock_securite_heating_pad',
            field=models.PositiveIntegerField(blank=True, help_text='Marge ajoutée au point de commande calculé. Vide = marge de 0.', null=True, verbose_name='stock de sécurité — heating pad'),
        ),
    ]
