# Generated by Django 5.2.17 on 2026-09-09 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0004_fournisseur_cout_unitaire_flexitank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='cout_unitaire_flexitank',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Coût d'une unité Flexitank chez ce fournisseur. Vide = valeur immobilisée affichée « — » pour ce type.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coût unitaire — flexitank'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='cout_unitaire_heating_pad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Coût d'une unité Heating pad chez ce fournisseur. Vide = valeur immobilisée affichée « — » pour ce type.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coût unitaire — heating pad'),
        ),
    ]
