# Generated by Django 5.2.17 on 2026-09-04 01:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='supprimé le')),
                ('numero_serie', models.CharField(db_index=True, help_text="Tel qu'imprimé par le fournisseur.", max_length=100, verbose_name='numéro de série')),
                ('code_interne', models.CharField(blank=True, help_text='Identifiant interne généré (QR), optionnel.', max_length=32, null=True, unique=True, verbose_name='code interne')),
                ('type_article', models.CharField(choices=[('FLEXITANK', 'Flexitank'), ('HEATING_PAD', 'Heating pad')], max_length=20, verbose_name="type d'article")),
                ('statut', models.CharField(choices=[('EN_STOCK', 'En stock'), ('SORTIE', 'Sorti')], default='EN_STOCK', max_length=20, verbose_name='statut')),
                ('date_entree', models.DateField(verbose_name="date d'entrée")),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='date de sortie')),
                ('emplacement', models.CharField(blank=True, help_text='Réservé v2.', max_length=100, verbose_name='emplacement')),
                ('reference_lot', models.CharField(blank=True, max_length=100, verbose_name='référence de lot')),
                ('attributs', models.JSONField(blank=True, default=dict, help_text='Capacité, type BL/BD, air vent, date de fabrication…', verbose_name='attributs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites_stock', to='fournisseurs.fournisseur', verbose_name='fournisseur')),
            ],
            options={
                'verbose_name': 'unité de stock',
                'verbose_name_plural': 'unités de stock',
                'ordering': ['-date_entree', 'numero_serie'],
                'indexes': [models.Index(fields=['type_article', 'statut'], name='stock_unite_type_statut_idx')],
                'constraints': [models.UniqueConstraint(fields=('fournisseur', 'numero_serie'), name='stock_unitestock_unique_numero_par_fournisseur')],
            },
        ),
    ]
