# Generated by Django 5.2.17 on 2026-09-04 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorties', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unitestock',
            name='sortie',
            field=models.ForeignKey(blank=True, help_text='Sortie non annulée en cours ; redevient nul après un retour ou une annulation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites', to='sorties.sortie', verbose_name='sortie en cours'),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('RETOUR', 'Retour'), ('ANNULATION_ENTREE', "Annulation d'entrée"), ('ANNULATION_SORTIE', 'Annulation de sortie')], max_length=20, verbose_name='type de mouvement')),
                ('date_mouvement', models.DateTimeField(help_text="Date métier de l'évènement (peut différer de la saisie, ex. un retour signalé après coup).", verbose_name='date du mouvement')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enregistré le')),
                ('sortie', models.ForeignKey(blank=True, help_text="Sortie à l'origine du mouvement (SORTIE, RETOUR, ANNULATION_SORTIE).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='sorties.sortie', verbose_name='sortie')),
                ('unite_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.unitestock', verbose_name='unité de stock')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-date_mouvement'],
                'indexes': [models.Index(fields=['unite_stock', 'date_mouvement'], name='stock_mouve_unite_s_154df8_idx')],
            },
        ),
    ]
