# Generated by Django 5.2.17 on 2026-09-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0001_initial'),
        ('stock', '0002_unitestock_sortie_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='reception',
            field=models.ForeignKey(blank=True, help_text="Réception à l'origine du mouvement (ENTREE, ANNULATION_ENTREE).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='receptions.reception', verbose_name='réception'),
        ),
        migrations.AddField(
            model_name='unitestock',
            name='reception',
            field=models.ForeignKey(blank=True, help_text="Réception d'origine (arrivage, saisie manuelle ou reprise).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='receptions.reception', verbose_name='réception'),
        ),
    ]
