# Generated by Django 5.2.17 on 2026-09-04 01:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('RESTAURATION', 'Restauration'), ('AUTRE', 'Autre')], max_length=20, verbose_name='action')),
                ('app', models.CharField(help_text='ex. fournisseurs, clients, stock', max_length=50, verbose_name='app')),
                ('objet_type', models.CharField(help_text='ex. Fournisseur, UniteStock', max_length=100, verbose_name="type d'objet")),
                ('objet_id', models.CharField(max_length=64, verbose_name="identifiant de l'objet")),
                ('resume', models.CharField(blank=True, max_length=255, verbose_name='résumé')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='données')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name': "historique d'action",
                'verbose_name_plural': 'historique des actions',
                'ordering': ['-date'],
            },
        ),
    ]
