# Generated by Django 5.2.17 on 2026-09-04 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueaction',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_historique', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['app', 'objet_type', 'objet_id'], name='common_hist_app_5c63f9_idx'),
        ),
    ]
