# Generated by Django 5.2.17 on 2026-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueaction',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('RESTAURATION', 'Restauration'), ('VALIDATION', 'Validation'), ('ANNULATION', 'Annulation'), ('RETOUR', 'Retour'), ('AUTRE', 'Autre')], max_length=20, verbose_name='action'),
        ),
    ]
