# Generated by Django 5.2.17 on 2026-09-15 09:27

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_historiqueaction_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('cle', models.CharField(max_length=255, verbose_name="clé d'idempotence")),
                ('methode', models.CharField(max_length=10, verbose_name='méthode HTTP')),
                ('chemin', models.CharField(max_length=255, verbose_name='chemin')),
                ('statut_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='code HTTP renvoyé')),
                ('corps', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='corps de la réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='réponse enregistrée le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "clé d'idempotence",
                'verbose_name_plural': "clés d'idempotence",
                'indexes': [models.Index(fields=['date_creation'], name='common_idem_date_cr_511de2_idx')],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'cle'), name='uniq_idempotence_par_utilisateur')],
            },
        ),
    ]
