# Generated by Django 5.2.17 on 2026-09-04 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('code_hache', models.CharField(max_length=128, verbose_name='code (haché)')),
                ('date_expiration', models.DateTimeField(verbose_name='expire le')),
                ('tentatives', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('utilise_le', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_reinitialisation', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'code de réinitialisation',
                'verbose_name_plural': 'codes de réinitialisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
