# Generated by Django 5.2.17 on 2026-09-04 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='supprimé le')),
                ('reference', models.CharField(editable=False, help_text='Générée automatiquement, ex. SOR-2026-0001.', max_length=30, unique=True, verbose_name='référence')),
                ('projet', models.CharField(help_text="Texte libre, autocomplété depuis l'historique.", max_length=200, verbose_name='projet')),
                ('trd', models.CharField(help_text='Référence saisie à chaque sortie.', max_length=100, verbose_name='TRD')),
                ('date_sortie', models.DateField(verbose_name='date de sortie')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('annule_le', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('motif_annulation', models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_annulees', to=settings.AUTH_USER_MODEL, verbose_name='annulée par')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties', to='clients.client', verbose_name='client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_creees', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_validees', to=settings.AUTH_USER_MODEL, verbose_name='validée par')),
            ],
            options={
                'verbose_name': 'sortie',
                'verbose_name_plural': 'sorties',
                'ordering': ['-date_sortie', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneSortie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name='ajoutée le')),
                ('unite_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_sortie', to='stock.unitestock', verbose_name='unité de stock')),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sorties.sortie', verbose_name='sortie')),
            ],
            options={
                'verbose_name': 'ligne de sortie',
                'verbose_name_plural': 'lignes de sortie',
                'ordering': ['ajoute_le'],
                'constraints': [models.UniqueConstraint(fields=('sortie', 'unite_stock'), name='sorties_lignesortie_unique_par_sortie')],
            },
        ),
    ]
