# Generated by Django 5.2.17 on 2026-09-04 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='supprimé le')),
                ('reference', models.CharField(editable=False, help_text='Générée automatiquement, ex. REC-2026-0001.', max_length=30, unique=True, verbose_name='référence')),
                ('nature', models.CharField(choices=[('ARRIVAGE', 'Arrivage'), ('SAISIE', 'Saisie manuelle'), ('REPRISE', "Reprise de l'existant")], max_length=20, verbose_name='nature')),
                ('reference_fournisseur', models.CharField(blank=True, help_text='Ex. EBT260407.', max_length=100, verbose_name='référence fournisseur')),
                ('date_reception', models.DateField(verbose_name='date de réception')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('quantite_annoncee', models.PositiveIntegerField(blank=True, help_text='Lue sur le document (ex. « 131 SETS »). Sert de contrôle de comptage, non bloquant.', null=True, verbose_name='quantité annoncée')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('annule_le', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('motif_annulation', models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_annulees', to=settings.AUTH_USER_MODEL, verbose_name='annulée par')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_creees', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('fournisseur', models.ForeignKey(blank=True, help_text='Requis pour un arrivage ou une saisie ; nul pour une reprise (fournisseur porté par chaque ligne).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='fournisseurs.fournisseur', verbose_name='fournisseur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_validees', to=settings.AUTH_USER_MODEL, verbose_name='validée par')),
            ],
            options={
                'verbose_name': 'réception',
                'verbose_name_plural': 'réceptions',
                'ordering': ['-date_reception', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneReception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('numero_serie', models.CharField(max_length=100, verbose_name='numéro de série')),
                ('type_article', models.CharField(choices=[('FLEXITANK', 'Flexitank'), ('HEATING_PAD', 'Heating pad')], max_length=20, verbose_name="type d'article")),
                ('statut_ligne', models.CharField(choices=[('OK', 'OK'), ('DOUBLON', 'Doublon'), ('FORMAT_INVALIDE', 'Format invalide'), ('A_VERIFIER', 'À vérifier')], default='OK', max_length=20, verbose_name='statut')),
                ('source', models.CharField(choices=[('EXTRACTION', 'Extraction automatique'), ('PLAGE', 'Plage'), ('MANUEL', 'Saisie manuelle'), ('REPRISE', 'Reprise')], max_length=20, verbose_name='source')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name='ajoutée le')),
                ('fournisseur', models.ForeignKey(blank=True, help_text="Renseigné pour une reprise (une ligne peut venir d'un fournisseur différent de l'en-tête) ; sinon hérité de la réception à la validation.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_reception', to='fournisseurs.fournisseur', verbose_name='fournisseur')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='receptions.reception', verbose_name='réception')),
            ],
            options={
                'verbose_name': 'ligne de réception',
                'verbose_name_plural': 'lignes de réception',
                'ordering': ['ajoute_le'],
            },
        ),
    ]
