# Generated by Django 5.2.17 on 2026-09-04 16:55

import apps.receptions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='fichier',
            field=models.FileField(blank=True, help_text="PDF d'arrivage — requis pour nature=ARRIVAGE, absent sinon.", null=True, upload_to='receptions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.receptions.models.valider_taille_fichier], verbose_name='fichier'),
        ),
    ]
