# Generated by Django 5.2.17 on 2026-09-10 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('endpoint', models.TextField(unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='clé publique (p256dh)')),
                ('auth', models.CharField(max_length=255, verbose_name='secret (auth)')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_push', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'abonnement web push',
                'verbose_name_plural': 'abonnements web push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('type', models.CharField(choices=[('MOUVEMENT_ENTREE', 'Réception validée'), ('MOUVEMENT_SORTIE', 'Sortie validée'), ('SEUIL_ATTEINT', 'Seuil de réapprovisionnement atteint'), ('STOCK_EPUISE', 'Stock épuisé')], max_length=20, verbose_name='type')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('corps', models.CharField(blank=True, max_length=500, verbose_name='corps')),
                ('lien', models.CharField(blank=True, help_text="Chemin in-app vers l'objet concerné (ex. /sorties/<id>, /previsions).", max_length=200, verbose_name='lien')),
                ('lu', models.BooleanField(default=False, verbose_name='lu')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'lu', '-created_at'], name='notificatio_destina_a5756e_idx')],
            },
        ),
    ]
